---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/lectures":
    get:
      summary: list lectures
      responses:
        '200':
          description: successful
    post:
      summary: create lecture
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                image_url:
                  type: string
                description:
                  type: string
                web_link:
                  type: string
                price:
                  type: number
                  format: float
                lecture_id:
                  type: number
              required:
              - lecture_id
              - date
              - city
  "/api/v1/lectures/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show lecture
      responses:
        '200':
          description: successful
  "/api/v1/users/{user_id}/reservations":
    parameters:
    - name: user_id
      in: path
      description: user_id
      required: true
      schema:
        type: string
    get:
      summary: list reservations
      responses:
        '200':
          description: successful
    post:
      summary: create reservation
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                lecture_id:
                  type: number
                date:
                  type: string
                  format: date
                city:
                  type: string
              required:
              - lecture_id
              - date
              - city
servers:
- url: http://127.0.0.1:3000
