#
# Make a copy of this file, change its name to database.yml and configure it with your own username and password below
#

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: book-an-appointment_app_development
test:
  <<: *default
  database: book-an-appointment_app_test
production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>